 -- SQL TASKS: PRACTICE QUESTIONS

-- Q1. List all customer names along with their cities.

-- Solution:
SELECT 
	 customerName,
     city
FROM customers;


-- Q2. Retrieve a list of customers and their associated sales representative.

-- Solution:
SELECT DISTINCT
	customerName,
	salesRepEmployeeNumber
FROM customers;
        
        
-- Q3. Find all customers who have placed orders, including their names, order, numbers and order dates;

-- Solution:
SELECT
	customers.customerNumber AS customer_number,
	customers.customerName AS customer_name,
    orders.orderNumber,
    orders.orderDate
FROM customers
	LEFT JOIN orders
		ON customers.customerNumber = orders.customerNumber
GROUP BY
		customers.customerNumber,
		orders.orderNumber,
		orders.orderDate ;
        
        
-- Q4. Determine how many orders each customer has placed.

-- Solution:
SELECT 
	customers.customerNumber,
    customers.customerName,
    COUNT(DISTINCT orders.orderNumber) AS count_of_orders
FROM customers
	LEFT JOIN orders
		ON customers.customerNumber = orders.customerNumber
GROUP BY 
    customers.customerNumber;
    
    
-- Q5. Find orders with total value greater than $5,000. Include thecustomer name, order number, and total value.

-- Solution: 
SELECT
	customers.customerName AS customer_name,
    customers.customerNumber AS customer_number,
    orderdetails.orderNumber AS order_number,
	SUM(orderdetails.priceEach) AS total_value,
    SUM(orderdetails.quantityOrdered) AS total_quantity_ordered
FROM orderdetails
	LEFT JOIN orders
		ON orderdetails.orderNumber = orders.orderNumber
	LEFT JOIN customers
		ON orders.customerNumber = customers.customerNumber
GROUP BY 
	customers.customerName,
    customers.customerNumber,
    orderdetails.orderNumber;

-- Q6. Find orders where the shipping date is after the required date. Include order numbers and delay durations.

-- Solution:
SELECT
	orderNumber,
    requiredDate,
    shippedDate
FROM orders
WHERE shippedDate > requiredDate;



-- Q7. Determine the top 3 products that generated the most revenue.

-- Solulion:
SELECT
    productLine,
    products.productName AS product_name,
    SUM(priceEach) AS total_revenue
FROM products
	LEFT JOIN orderdetails
		ON products.productCode = orderdetails.productCode
GROUP BY 
	productLine, 
    products.productName
ORDER BY SUM(priceEach) DESC
LIMIT 3;

-- Q8. Determine the total revenue for each product line.

-- Solution:
SELECT 
	products.productLine,
    products.productCode,
    SUM(orderdetails.priceEach) AS total_revenue
FROM products
	LEFT JOIN orderdetails
		ON products.productCode = orderdetails.productCode
GROUP BY 
	products.productLine,
    products.productCode
ORDER BY 
	total_revenue DESC;


-- Q9. Identify the top 5 customers based on total order value.

-- Solution:
SELECT
    orders.orderNumber,
    orders.customerNumber,
    customers.customerName,
    SUM(orderdetails.quantityOrdered) AS total_order_value
FROM
    orderdetails
        LEFT JOIN orders 
			ON orderdetails.orderNumber = orders.orderNumber
        LEFT JOIN customers 
			ON orders.customerNumber = customers.customerNumber
GROUP BY orders.orderNumber
ORDER BY orders.customerNumber DESC
LIMIT 5;

-- Q10. Find the total revenue generated by each sales representative.

-- Solution:

	
